name: Dynamic Profile

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  github-activity:
    runs-on: ubuntu-latest
    name: Add activity stats
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}